<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  <Version>0.1.0</Version></PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="BeamerPresenter.Web.Tests" />
    <PackageReference Include="MudBlazor" />
    <ProjectReference Include="..\BeamerPresenter.Application\BeamerPresenter.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <EmbeddedResource Include="UiStrings.tsv" />
  </ItemGroup>
</Project>
