<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup><Compile Include="../BeamerPresenter.Shared/RecordingApplicationUpdates.cs" Link="RecordingApplicationUpdates.cs" /></ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\src\BeamerPresenter.Infrastructure\BeamerPresenter.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\BeamerPresenter.Web\BeamerPresenter.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Playwright" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\src\BeamerPresenter.Web\wwwroot\**\*">
      <Link>wwwroot\_content\BeamerPresenter.Web\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="$(NuGetPackageRoot)mudblazor\$(MudBlazorVersion)\staticwebassets\**\*">
      <Link>wwwroot\_content\MudBlazor\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
