// <auto-generated />
using System;
using BeamerPresenter.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BeamerPresenter.Infrastructure.Migrations
{
    [DbContext(typeof(PresenterDbContext))]
    [Migration("20260926094008_AddLanguagePreference")]
    partial class AddLanguagePreference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("BeamerPresenter.Domain.MediaFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeSubdirectories")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("MediaFolders");
                });

            modelBuilder.Entity("BeamerPresenter.Domain.NewsItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Permanent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ValidUntil")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ValidFrom", "ValidUntil", "Priority");

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("BeamerPresenter.Domain.PlaybackHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan?>("ActualEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("ActualStart")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalSourceKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Interrupted")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("PlannedEnd")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("PlannedStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaybackReason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSourceKey", "StartedUtc");

                    b.HasIndex("MediaId", "StartedUtc");

                    b.ToTable("PlaybackHistory");
                });

            modelBuilder.Entity("BeamerPresenter.Domain.PresenterSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AggressiveTopmost")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowLanAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AlwaysOnTop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("ChromePath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClipLengthMaxSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(600);

                    b.Property<int>("ClipLengthMinSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(420);

                    b.Property<string>("FfprobePath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguagePreference")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("MediaFolder")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("MonitorDeviceName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreventDisplaySleep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("PreventSystemSleep")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("QueueTargetLength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<int>("ShortVideoThresholdSeconds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(600);

                    b.Property<int>("TimeCooldownMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(60);

                    b.Property<int>("VideoCooldownCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(10);

                    b.Property<int>("WebPort")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("BeamerPresenter.Domain.QueueEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("EndPosition")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSourceKey")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceType")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("StartPosition")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status", "SortOrder");

                    b.ToTable("QueueEntries");
                });

            modelBuilder.Entity("BeamerPresenter.Domain.VideoAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AudioChannels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioCodec")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Container")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FrameRate")
                        .HasColumnType("REAL");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastScannedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastWriteUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaybackStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProbeError")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProbeStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoCodec")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VideoHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VideoWidth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("YouTubeSourceKey")
                        .HasMaxLength(19)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullPath")
                        .IsUnique();

                    b.HasIndex("YouTubeSourceKey")
                        .IsUnique();

                    b.ToTable("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
